# This is the test file for mafiaGameClass.py. This tests all the functionalities of that
# class. Formatting is not tested. 

from mafiaGameClass import mafiaGameClass as game

test = game()
test.addTownPlayer("Zexy")
test.addTownPlayer("Piko")
test.addTownPlayer("Caps")
test.addTownPlayer("ME")
test.addTownPlayer("Elementar")
test.addTownPlayer("Eevee")
test.addTownPlayer("HD")
test.addTownPlayer("FA")
test.addTownPlayer("MCH")
test.addMafiaPlayer("leetic")
test.addMafiaPlayer("Life")
test.addIndPlayer("Mido")
test.addIndPlayer("Slife")
test.setHost("The War Room")
test.nextPhase()
print("Day %r" % test.getCurrPhase())
print("Town count: %r " % test.currTownCount())
print("Current Town members: %r " % test.currTownList())
print("Current Mafia count: %r " % test.currMafiaCount())
print("Current Mafia members: %r " % test.currMafiaList())
print("Current Indep count: %r " % test.currIndCount())
print("Current Indep members: %r " % test.currIndList())	
test.removeTown("HD")
print("HD has been lynched! HD is town!")
print("Current Town members: %r " % test.currTownList())
print("Town count: %r " %test.currTownCount())
print("Night %r" % test.getCurrPhase())
test.removeTown("FA")
test.nextPhase()
print("Day %r" % test.getCurrPhase())
print("FA has been night-killed! FA was town!")
print("Current Town members: %r " % test.currTownList())
print("Town count: %r " % test.currTownCount())
test.removeMafia("leetic")
print("leetic has been lynched! leetic was mafia!")
print("Current Mafia count: %r " % test.currMafiaList())
print("Current Dead Mafia members: %r " % test.getDeadMafia())
print("Current Dead Town members: %r " % test.getDeadTown())
print("Current Dead Indep members: %r " % test.getDeadInd())
print("Night %r" % test.getCurrPhase())
test.removeTown("ME")
test.nextPhase()
print("Day %r" % test.getCurrPhase())
print("ME has been night-killed! ME was town!")
print("Current Town members: %r " % test.currTownList())
print("Town count: %r " % test.currTownCount())
test.removeInd("Slife")
print("Slife has been lynched! Slife was indep!")
print("Current Mafia Indep: %r " % test.currMafiaList())
print("Current Dead Mafia members: %r " % test.getDeadMafia())
print("Current Dead Town members: %r " % test.getDeadTown())
print("Current Dead Indep members: %r " % test.getDeadInd())
print("Night %r" % test.getCurrPhase())
test.removeTown("MCH")
test.nextPhase()
print("Day %r" % test.getCurrPhase())
print("MCH has been night-killed! MCH was town!")
print("Current Town members: %r " % test.currTownList())
print("Town count: %r " % test.currTownCount())
test.removeMafia("Life")
print("Life has been lynched! Life was mafia!")
test.setVictor(test.currTownList())
test.setVictor(test.getDeadTown())
test.setVictor("Mido")
print("%r won the game!" % test.getVictor())
print("This game has been hosted by: %r" % test.getHosts())